cloudforet-io/plugin-nhncloud-inven-collector

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/check-pull-request.yml
.github/workflows/push_build_dev.yaml

- update slack notification to discord notification
- add push trigger event only in forked repository for pushing dockerhub image automatically
- add repository owner check logic for discord conditional notification
- delete scan action

Add github actions script

---

managed_resource/schema/nhncloud_app_key.yaml
src/plugin/conf/cloud_service_conf.py
src/plugin/connector/api_gateway/api_key_connector.py
src/plugin/connector/api_gateway/service_connector.py
src/plugin/connector/api_gateway/usage_plan_connector.py
src/plugin/connector/email/category_connector.py
src/plugin/connector/email/tag_connector.py
src/plugin/connector/email/template_connector.py
src/plugin/connector/push/tag_connector.py
src/plugin/connector/push/token_connector.py
src/plugin/manager/__init__.py
src/plugin/manager/api_gateway/api_key_manager.py
src/plugin/manager/api_gateway/service_manager.py
src/plugin/manager/api_gateway/usage_plan_manager.py
src/plugin/manager/email/category_manager.py
src/plugin/manager/email/tag_manager.py
src/plugin/manager/email/template_manager.py
src/plugin/manager/push/tag_manager.py
src/plugin/manager/push/token_manager.py
src/plugin/metadata/api_gateway/api_key.yaml
src/plugin/metadata/api_gateway/service.yaml
src/plugin/metadata/api_gateway/usage_plan.yaml
src/plugin/metadata/email/category.yaml
src/plugin/metadata/email/tag.yaml
src/plugin/metadata/email/template.yaml
src/plugin/metadata/push/tag.yaml
src/plugin/metadata/push/token.yaml

- api gateway (api key, service, usage plan)
- email (category, tag, template)
- push (tag, token)
- add schema properties for paas service request (service-wide secret value)
static asset PR : https://github.com/cloudforet-io/static-assets/pull/2

Add Notification, Application Service resources

---

managed_resource/plugin/collector.yaml
managed_resource/provider/nhncloud.yaml

- add plugin yaml file
resolve #14

Add plugin definition yaml file

---

src/plugin/connector/image/image_connector.py
src/plugin/connector/instance/instance_AZ_connector.py
src/plugin/connector/instance/instance_connector.py
src/plugin/connector/instance/keypair_connector.py
src/plugin/manager/image/image_manager.py
src/plugin/manager/instance/AZ_manager.py
src/plugin/manager/instance/instance_manager.py
src/plugin/manager/instance/keypair_manager.py
src/plugin/metadata/image/image.yaml
src/plugin/metadata/instance/instance.yaml
src/plugin/metadata/instance/instance_AZ_resource.yaml
src/plugin/metadata/instance/keypair.yaml

- instance (list, AZ, keypair)
- image

Add Instance, Image service resources

---

src/plugin/connector/nks/nks_connector.py
src/plugin/connector/nks/nks_group_connector.py

Add NHN k8s Service

---

src/plugin/connector/block_storage/block_storage_connector.py
src/plugin/connector/block_storage/block_storage_snapshots_connector.py
src/plugin/connector/block_storage/block_storage_type_connector.py
src/plugin/manager/block_storage/block_storage_manager.py
src/plugin/manager/block_storage/block_storage_snapshots_manager.py
src/plugin/manager/block_storage/block_storage_type_manager.py
src/plugin/metadata/block_storage/block_storage.yaml
src/plugin/metadata/block_storage/block_storage_type.yaml
src/plugin/metadata/block_storage/snapshots.yaml

- Block Storage (Type, List, Snapshots)

Add Block Storage

---

src/plugin/connector/base.py

Added code that logs and raises an exception when a token issuance issue occurs.

Add Raise Exception code in NHNCloudBaseConnector

---

.github/workflows/dispatch_release.yaml

feat: add release github actions script

---

src/plugin/manager/__init__.py
src/plugin/manager/nks/group_manager.py
src/plugin/manager/nks/nks_manager.py
src/plugin/metadata/nks/group.yaml
src/plugin/metadata/nks/nks.yaml

fix: add nks managers with labels

---

src/plugin/conf/cloud_service_conf.py
src/plugin/main.py
src/plugin/manager/base.py

- add collecting region information logic

Add region collecting logic

---

src/plugin/manager/email/category_manager.py
src/plugin/manager/email/tag_manager.py
src/plugin/manager/email/template_manager.py
src/plugin/manager/push/tag_manager.py
src/plugin/manager/push/token_manager.py

- ignore collecting request when threre is no additional auth key and only app key is exists
- Email, Push resources

Push, Email error handling

---

src/plugin/manager/__init__.py
src/plugin/manager/nks/group_manager.py
src/plugin/manager/nks/nks_manager.py
src/plugin/metadata/nks/group.yaml
src/plugin/metadata/nks/nks.yaml

- Refactor TODO paging in LoadBalancer Secrets
생략

Fix lost nks managers with labels

---

src/plugin/connector/object_storage/container_connector.py
src/plugin/metadata/object_storage/container.yaml

Signed-off-by: andy000923 <andy000923@gmail.com>

Add Object Storage connector & metadata

---

src/plugin/connector/loadbalancer/secret_connector.py

- paging handler in LoadBalancer Secret

Fix paging in LoadBalancer Secret (TODO)

---

managed_resource/schema/nhncloud_object_storage_access_key.yaml
managed_resource/schema/nhncloud_service_account.yaml
src/plugin/conf/cloud_service_conf.py
src/plugin/connector/object_storage/container_connector.py
src/plugin/manager/__init__.py
src/plugin/manager/base.py
src/plugin/manager/object_storage/container_manager.py

Add object storage collecting logic

---

managed_resource/plugin/collector.yaml

Add collector description

---

src/plugin/connector/loadbalancer/listener_connector.py
src/plugin/manager/loadbalancer/loadbalancer_manager.py
src/plugin/metadata/loadbalancer/listeners.yaml
src/plugin/metadata/loadbalancer/loadbalancer.yaml

Additional listener inquiry API in LoadBalancer

Update metadata with listeners

---

src/plugin/manager/email/category_manager.py
src/plugin/manager/email/tag_manager.py
src/plugin/manager/email/template_manager.py
src/plugin/manager/push/tag_manager.py
src/plugin/manager/push/token_manager.py

- replace key check func correctly.

Update dictionary key check

---

README.md

Signed-off-by: andy000923 <andy000923@gmail.com>

Add README for NHN Cloud Plugin

---

src/plugin/manager/instance/instance_manager.py

- Add key existence check logic.

Check key existence in instance resource
